### PR TITLE
setting up build & QA script

### PR DESCRIPTION
**Pull request by felipesanches**
@laerm0 @vv-monsalve @eliheuer @bghryct

### CODE REVIEW

**Comment by felipesanches** [comment]
This is being built at https://travis-ci.com/felipesanches/Russolo

I'll be further tweaking the setup. This is still experimental.

**Comment by felipesanches** [comment]
OK. I am happy with this setup!

**Comment by felipesanches** [comment]
This PR assumes OFL licensing and also fixes a few FB FAILs by editing the `.glyphs` file.

**Comment by felipesanches** [comment]
@laerm0, I won't be editing this anymore, so it is in a good state for you to review and give some feedback. I'd also be glad to head from @eliheuer, @vv-monsalve and @bghryct

be sure to read the Travis build log at https://travis-ci.com/felipesanches/Russolo/builds/132577283

**Comment by laerm0** [comment]
Awesome, thanks @felipesanches !

**Comment by felipesanches** [comment]
now you should enable https://travis-ci.com/laerm0/Russolo/

**Comment by felipesanches** [comment]
or maybe https://travis-ci.org/laerm0/Russolo/

I always get confused about the difference between the `.com` and the `.org` domains for Travis.

**Pull request merged**
